export const environment = {
  fibrilContractAddress: process.env.VUE_APP_FIBRIL_CONTRACT_ADDRESS,
  daiTokenAddress: process.env.VUE_APP_DAI_TOKEN_ADDRESS,
  usdtTokenAddress: process.env.VUE_APP_USDT_TOKEN_ADDRESS,
  usdcTokenAddress: process.env.VUE_APP_USDC_TOKEN_ADDRESS,
  nullAddress: process.env.VUE_APP_NULL_ADDRESS,
  nativeTokenAddress: process.env.VUE_APP_NATIVE_TOKEN_ADDRESS,
  moralisServerUrl: process.env.VUE_APP_MORALIS_SERVER_URL,
  moralisAppId: process.env.VUE_APP_MORALIS_APP_ID,
  web3StorageToken: process.env.VUE_APP_WEB3_STORAGE_TOKEN,
  chainId: process.env.VUE_APP_CHAIN_ID,
  explorerUrl: process.env.VUE_APP_EXPLORER_URL,
  priceFeedContractAddress: process.env.VUE_APP_PRICE_FEED_CONTRACT_ADDRESS,
  networkName: process.env.VUE_APP_NETWORK_NAME,
}
